/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_bits_com_opencvnativeandroid_NativeClass */

#ifndef _Included_project_bits_com_opencvnativeandroid_NativeClass
#define _Included_project_bits_com_opencvnativeandroid_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_bits_com_opencvnativeandroid_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_project_bits_com_opencvnativeandroid_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     project_bits_com_opencvnativeandroid_NativeClass
 * Method:    getTimeFromJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_project_bits_com_opencvnativeandroid_NativeClass_getTimeFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
